### PR TITLE
Fix licenseHeader for Kotlin code starting with `@file:...`

### LINKED ISSUE #136: Kotlin file could start with `@file:...` instead of `package ...`
The regex for finding the top of the file (where the license should go) doesn't work when you start your file with:
```kotlin
@file:JvmName("SomeFileName")
package ... // ect...
```

The default header regex for kotlin should support starting the file with the `@file` annotation.
As a note, the compiler will only let you legally put `@file:...` annotations above the package statement.

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes #136

### CODE REVIEW

**Comment by nedtwigg** [comment]
Can you add a changelog entry under `3.6.0-SNAPSHOT` for `plugin-gradle/CHANGES.md`.  Otherwise LGTM, thanks!

**Comment by JLLeitschuh** [comment]
Done!

File: plugin-gradle/src/main/java/com/diffplug/gradle/spotless/KotlinExtension.java [hunk 1]
```diff
@@ -25,18 +25,20 @@
 import com.diffplug.spotless.kotlin.KtLintStep;
 
 public class KotlinExtension extends FormatExtension {
+	// The delimiter has the '^' prepended to the regex where the pattern is compiled.
```
Comment (jbduncan) [inline plugin-gradle/src/main/java/com/diffplug/gradle/spotless/KotlinExtension.java]: It took me a while to understand what this comment was saying, so I wonder if it would be clearer if it was worded something like this:

> // '^' is prepended to the regex in LICENSE_HEADER_DELIMITER later in FormatExtension.licenseHeader(String, String)

File: plugin-gradle/src/test/java/com/diffplug/gradle/spotless/KotlinExtensionTest.java [hunk 2]
```diff
@@ -40,4 +44,29 @@ public void integration() throws IOException {
...
+				"    }",
+				"}");
+		final File testFile = write("src/main/kotlin/test.kt", getTestResource("kotlin/licenseheader/KotlinCodeWithoutHeader.test"));
+		final String original = read(testFile.toPath());
+		gradleRunner().withArguments("spotlessApply").build();
+		final String result = read(testFile.toPath());
+		// Make sure the header gets added.
+		Assertions.assertThat(result).startsWith(HEADER);
+		// Make sure that the rest of the file is still there with nothing removed.
+		Assertions.assertThat(result).endsWith(original);
```
Comment (jbduncan) [inline plugin-gradle/src/test/java/com/diffplug/gradle/spotless/KotlinExtensionTest.java]: AFAICT, these two assertions don't guard against the case where unrelated text gets inserted in between the header and the rest of the original file contents, accidentally or otherwise.

Thus I wonder if it's worth testing that `original` directly follows `HEADER`.

(If so, one might be able to do this using String character indexes somehow, or alternatively checking that the file contains exactly as many lines as `HEADER + original`...)

File: plugin-gradle/src/main/java/com/diffplug/gradle/spotless/KotlinExtension.java (hunk 1 above)
Comment (JLLeitschuh) [reply plugin-gradle/src/main/java/com/diffplug/gradle/spotless/KotlinExtension.java]: Sure, sounds good.

File: plugin-gradle/src/test/java/com/diffplug/gradle/spotless/KotlinExtensionTest.java (hunk 2 above)
Comment (JLLeitschuh) [reply plugin-gradle/src/test/java/com/diffplug/gradle/spotless/KotlinExtensionTest.java]: Interesting thought. I'll add something to assert that.

Comment (JLLeitschuh) [reply plugin-gradle/src/test/java/com/diffplug/gradle/spotless/KotlinExtensionTest.java]: I've expanded this test.

**Comment by JLLeitschuh** [comment]
Should be all cleaned up now!

**Comment by jbduncan** [comment]
Looks great to me now @JLLeitschuh. Thanks!

**Comment by nedtwigg** [comment]
I'll release as a bugfix later today.
