### PR TITLE
Reinstall node if necessary

### LINKED ISSUE #863: Prettier dies when directory is removed before `spotlessApply`
I'm using Spotless with Prettier in a Gradle submodule. (Another submodule also uses Spotless, but with Kotlin.)
My `build` task will clean the `/build` directory before starting, as the compiled Javascript resources will end up in there. However, it seems that Spotless first creates a directory `spotless-node-modules-prettier-format` in `/build`, which will then get cleaned by the `build` task, and then the actual `spotlessCheck` fails quite ugly:

```
Step 'prettier-format' found problem in 'frontend/src/components/App.tsx':
Failed to launch npm command 'npm start --scripts-prepend-node-path=true'.
com.diffplug.spotless.npm.NpmProcess$NpmProcessException: Failed to launch npm command 'npm start --scripts-prepend-node-path=true'.
        at com.diffplug.spotless.npm.NpmProcess.npm(NpmProcess.java:66)
        at com.diffplug.spotless.npm.NpmProcess.start(NpmProcess.java:42)
        at com.diffplug.spotless.npm.NpmFormatterStepStateBase.npmRunServer(NpmFormatterStepStateBase.java:95)
        at com.diffplug.spotless.npm.PrettierFormatterStep$State.createFormatterFunc(PrettierFormatterStep.java:84)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:76)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:201)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:188)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:71)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:57)
[...]
Caused by: java.io.IOException: Cannot run program "/usr/bin/npm" (in directory "<snip>/frontend/build/spotless-node-modules-prettier-format"): error=2, File or directory not found
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.diffplug.spotless.npm.NpmProcess.npm(NpmProcess.java:64)
        ... 145 more
Caused by: java.io.IOException: error=2, File or directory not found
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 147 more
```

It seems that this only happens when I run `build` in more than this submodule.

Can Spotless be made to create that directory not in the configuration phase, but only when it actually runs?

Gradle: 7.0, but also observed with earlier versions
Spotless version: 5.12.4
OS: Latest Manjaro

### PR DESCRIPTION
**Pull request by fdw**
If node has been deleted between Spotless installing it and using it
(for example because React's `build` removes everything from the `build`
dir), it is not re-installed.

Fixes #863

### CODE REVIEW

**Comment by fdw** [comment]
I couldn't think of a good way to test this, unfortunately. If you have an idea, please share :)

File: lib/src/main/java/com/diffplug/spotless/npm/NodeServerLayout.java [hunk 1]
```diff
@@ -46,4 +46,8 @@ File serveJsFile() {
 	public File npmrcFile() {
 		return npmrcFile;
 	}
+
+	public static File getBuildDirFromNodeModulesDir(File nodeModulesDir) {
```
Comment (nedtwigg) [inline lib/src/main/java/com/diffplug/spotless/npm/NodeServerLayout.java:50]: make it package-private, not public

**Review by nedtwigg — CHANGES_REQUESTED** [review]
- Run `spotlessApply`
- Did you [integration test](https://github.com/diffplug/spotless/blob/main/CONTRIBUTING.md#gradle---locally) on your machine to confirm that it fixed your problem?

**Comment by fdw** [comment]
> Run spotlessApply

Oh, I'm so sorry. Fixed now.

> Did you integration test on your machine to confirm that it fixed your problem?

Yes, and it works :)

File: lib/src/main/java/com/diffplug/spotless/npm/NodeServerLayout.java (hunk 1 above)
Comment (fdw) [reply lib/src/main/java/com/diffplug/spotless/npm/NodeServerLayout.java]: Done.

**Comment by nedtwigg** [comment]
Shipped in `plugin-maven 2.11.1` and `plugin-gradle 5.12.5`

**Comment by fdw** [comment]
That was very quick and nice. Thank you very much!
