### PR TITLE
Fix ktlint 0.48

### LINKED ISSUE #1444: Support new way to disable rules in ktlint 0.48
- [ 6.12.1 ] spotless version

Currently, using the `ktlint_disabled_rules` causes many warnings to be printed in the console:
```
Property 'ktlint_disabled_rules' is deprecated: Update all your all '.editorconfig' files. See [link below]
```

https://pinterest.github.io/ktlint/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this

Following that, if I configure Spotless as below, the config is ignored and rules are still enabled.
```
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
        ktlint("0.48.0")
            .editorConfigOverride(
                mapOf(
                    "ktlint_standard_filename" to "disabled",
                ),
            )
    }
}
```

### PR DESCRIPTION
**Pull request by Sineaggi**
Fixes #1444 

We use ktlint's new rule execution api to construct rules that support the format in [ktlint's documentation](https://pinterest.github.io/ktlint/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this).

So for example, `ktlint_standard` will disable all the standard rules and `ktlint_standard_no-semi` would only disable the no semicolon rule.

Fixed a few deprecation warnings and added tests to verify the new rules work.

Bumps ktlint to `0.48.1`

### CODE REVIEW

**Comment by Sineaggi** [comment]
For the two rules that have deprecation (for removal) warnings,
```java
//noinspection deprecation
list.add(DisabledRulesEditorConfigPropertyKt.getDISABLED_RULES_PROPERTY());
//noinspection KotlinInternalInJava,deprecation
list.add(DisabledRulesEditorConfigPropertyKt.getKTLINT_DISABLED_RULES_PROPERTY());
```
we'll simply be removing them from the list of rules when they're removed.

File: lib/src/compatKtLint0Dot48Dot1/java/com/diffplug/spotless/glue/ktlint/compat/KtLintCompat0Dot48Dot1Adapter.java [hunk 1]
```diff
@@ -66,25 +91,18 @@ public String format(final String text, final String name, final boolean isScrip
...
 					RuleProvider::createNewRuleInstance).collect(
 							Collectors.toList()),
 					editorConfigOverrideMap);
 		}
 
-		return KtLint.INSTANCE.format(new KtLint.ExperimentalParams(
-				name,
-				text,
-				allRuleProviders,
-				userData,
```
Comment (twarner-sofi) [inline lib/src/compatKtLint0Dot48Dot1/java/com/diffplug/spotless/glue/ktlint/compat/KtLintCompat0Dot48Dot1Adapter.java:81]: Looks like `userData` is not getting passed into `KtLintRuleEngine`. Looks like userData is deprecated in ktlint so not sure if its needed any more.

**Comment by Sineaggi** [comment]
ktlint's new (non-deprecated) formatting api will always load the .editorconfig. In this case, the .editorconfig in the root folder is changing the behavior of the tests.

File: lib/src/compatKtLint0Dot48Dot1/java/com/diffplug/spotless/glue/ktlint/compat/KtLintCompat0Dot48Dot1Adapter.java (hunk 1 above)
Comment (Sineaggi) [reply lib/src/compatKtLint0Dot48Dot1/java/com/diffplug/spotless/glue/ktlint/compat/KtLintCompat0Dot48Dot1Adapter.java]: Looks like `userData` is being ignored either way under `0.48.x`

File: lib/build.gradle [hunk 2]
```diff
@@ -34,7 +34,7 @@ versionCompatibility {
 				'0.45.2',
 				'0.46.0',
 				'0.47.0',
-				'0.48.0',
+				'0.48.1',
```
Comment (davidburstrom) [inline lib/build.gradle:37]: If 0.48.0 and 0.48.1 are binary compatible (and as far as I can see from https://github.com/pinterest/ktlint/releases), I'd recommend that you keep the adapter version set to 0.48.0. Otherwise it appears as if the same adapter should be used for versions 0.47.x and 0.48.0 inclusive (see [manual for version-compatibility-gradle-plugin](https://github.com/davidburstrom/version-compatibility-gradle-plugin#:~:text=It%20is%20recommended%20that%20the%20compat%20version%20for%20each%20source%20set%20is%20the%20earliest%20version%20the%20adapter%20supports%2C%20for%20consistency)). In the test `works0_48_1` you would still verify that disabling works. If 0.48.0 is truly not supported, then it needs to be reflected in the code that selects the adapter.

File: lib/build.gradle [hunk 3]
```diff
@@ -105,10 +105,16 @@ dependencies {
 	flexmarkCompileOnly 'com.vladsch.flexmark:flexmark-all:0.62.2'
 }
 
+configurations.named('testCompatKtLint0Dot48Dot1Implementation').configure {
+	extendsFrom(configurations.testImplementation, configurations.compatKtLint0Dot48Dot1CompileOnly)
```
[the remark this answers is not in the document]
Comment (davidburstrom) [reply lib/build.gradle:109]: Regarding exposing the `compileOnly` libraries it makes perfect sense. I've had some thoughts about making the plugin export that automatically to the test implementation classpath, as it's likely that you'd want to refer to that version of the library as part of the test suite. Do you think it would make sense to automatically add a configuration called something like `compatXYZSpecific` that `compatXYZCompileOnly` and `testCompatXYZImplementation` would extend from? "Specific" is up for discussion.

[the remark this answers is not in the document]
Comment (davidburstrom) [reply lib/build.gradle:109]: 🤔 Having a `compatXYZSpecific` configuration would be quite flexible since everything is modular in nature. If you actually want a different library on the classpath, you simply don't need to add anything to `compatXYZSpecific`, but rather to the downstream configurations directly.

File: lib/build.gradle (hunk 2 above)
Comment (Sineaggi) [reply lib/build.gradle]: They are compatible, I've reverted out the renaming change.

Comment (davidburstrom) [reply lib/build.gradle]: Cool!

File: lib/build.gradle (hunk 3 above)
[the remark this answers is not in the document]
Comment (davidburstrom) [reply lib/build.gradle]: @Sineaggi Do you have any thoughts about my info-dump here? :)

[the remark this answers is not in the document]
Comment (Sineaggi) [reply lib/build.gradle]: @davidburstrom I had missed the `testCommonImplementation` configuration when looking thru the docs.

Also, I like the idea of the `compatXYZSpecific`.  `compatXYZCompileOnlyAndTestImplementation` maybe? :)

[the remark this answers is not in the document]
Comment (davidburstrom) [reply lib/build.gradle]: I'll see what I can do :) Naming is hard...

[the remark this answers is not in the document]
Comment (davidburstrom) [reply lib/build.gradle]: I've published version 0.4.0 of the plugin now, with support for `CompileAndTestOnly`. See https://github.com/davidburstrom/version-compatibility-gradle-plugin#compatibility-adapters.

**Comment by eirnym** [comment]
I've started the #1442 to introduce editorconfig support earlier and feel we need to join our efforts

**Comment by nedtwigg** [comment]
I just did a local test-merge between this PR and 1442

- #1442

and luckily the only conflict was a manageable one in `KtLintCompat0Dot48Dot0Adapter`. In my estimation, the other PR, #1442, is the harder one, so normally I would let that one merge first.

But, in this case, @davidburstrom is the original author and maintainer of the `KtlintStep`, and he has been engaged in this PR. So I the order of merging will be:

- this PR when @davidburstrom comments with "this PR is ready to merge"
- then #1442 when @eirnym has had a chance to fix the merge conflicts. Might be a good idea for you to review that PR too if you have time @davidburstrom, it is high quality and fixes the long-requested problem of `.editorconfig` integration

Sorry @eirnym, you got sort of a rough break to write a good and long-requested feature.

**Comment by eirnym** [comment]
@nedtwigg Thanks, this sounds like a good plan, as soon this PR will be merged, I'll merge `main` branch. 
@davidburstrom I'd be happy if you review my PR as well

PS: I kind'a expected to have some time break as well ;P

File: lib/build.gradle [hunk 4]
```diff
@@ -105,10 +105,16 @@ dependencies {
 	flexmarkCompileOnly 'com.vladsch.flexmark:flexmark-all:0.62.2'
 }
 
+configurations.named('testCompatKtLint0Dot48Dot0Implementation').configure {
```
Comment (davidburstrom) [inline lib/build.gradle:108]: This should no longer be necessary with version 0.4.0 of the version-compatibility-plugin, if the `compatKtLint0Dot48Dot0CompileOnly` is changed to `ompatKtLint0Dot48Dot0CompileAndTestOnly`.

File: lib/build.gradle [hunk 5]
```diff
@@ -105,10 +105,16 @@ dependencies {
...
+	extendsFrom(configurations.compatKtLint0Dot48Dot0CompileOnly)
+}
+
 // we'll hold the core lib to a high standard
 spotbugs { reportLevel = 'low' } // low|medium|high (low = sensitive to even minor mistakes)
 
-test { useJUnitPlatform() }
+tasks.withType(Test).configureEach {
```
Comment (davidburstrom) [inline lib/build.gradle:115]: This is good (other than also being required) :)

File: lib/src/testCompatKtLint0Dot48Dot0/java/com/diffplug/spotless/glue/ktlint/compat/KtLintCompat0Dot48Dot0AdapterTest.java [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+import java.util.Map;
+
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.io.TempDir;
+
+public class KtLintCompat0Dot48Dot0AdapterTest {
+	@Test
+	public void testDefaults(@TempDir Path path) throws IOException {
+		KtLintCompat0Dot48Dot0Adapter ktLintCompat0Dot48Dot0Adapter = new KtLintCompat0Dot48Dot0Adapter();
+		try (InputStream is = KtLintCompat0Dot48Dot0AdapterTest.class.getResourceAsStream("/empty_class_body.kt")) {
```
Comment (davidburstrom) [inline lib/src/testCompatKtLint0Dot48Dot0/java/com/diffplug/spotless/glue/ktlint/compat/KtLintCompat0Dot48Dot0AdapterTest.java:35]: What would you say about extracting this into a utility function? As far as I can tell, it's just a fairly condensed way of getting a String from a Java resource, but it's still verbose when it's duplicated.

**Comment by davidburstrom** [comment]
> this PR when @davidburstrom comments with "this PR is ready to merge"

I'm not sure if I should consider myself author/maintainer, but I'm happy to chime in. I don't have anything other than minor suggestions. After @Sineaggi has had a chance to look at those and do as he feels about them, I think this PR is ready to be merged.

**Comment by davidburstrom** [comment]
@eirnym I've looked through #1442 and it looks good. Let me know when the merge conflicts have been addressed, and then I'll have another go.

**Comment by eirnym** [comment]
@davidburstrom sweet! I'll address merge conflicts as soon as possible after this PR is merged.

File: lib/build.gradle (hunk 4 above)
Comment (Sineaggi) [reply lib/build.gradle]: I've used the latest plugin to clean this up. Thanks for the new configuration!

File: lib/src/testCompatKtLint0Dot48Dot0/java/com/diffplug/spotless/glue/ktlint/compat/KtLintCompat0Dot48Dot0AdapterTest.java (hunk 6 above)
Comment (Sineaggi) [reply lib/src/testCompatKtLint0Dot48Dot0/java/com/diffplug/spotless/glue/ktlint/compat/KtLintCompat0Dot48Dot0AdapterTest.java:35]: I could just inline the input, considering I inlined the formatting result.

Comment (davidburstrom) [reply lib/src/testCompatKtLint0Dot48Dot0/java/com/diffplug/spotless/glue/ktlint/compat/KtLintCompat0Dot48Dot0AdapterTest.java:35]: Even easier :)

File: lib/build.gradle (hunk 4 above)
Comment (davidburstrom) [reply lib/build.gradle]: No problem, I'm happy to improve the plugin :) I also improved the plugin documentation, fyi.

**Comment by davidburstrom** [comment]
> "this PR is ready to merge"

this PR is ready to merge

Nicely done @Sineaggi!

**Comment by Jolley71717** [comment]
I'm excited to see this get deployed. 

We've had some super nasty output from the `java.lang.IllegalArgumentException: Can not create an EditorConfigOverride without properties. Use 'emptyEditorConfigOverride' instead`

Thanks again for merging it.

**Comment by nedtwigg** [comment]
Published in `plugin-gradle 6.13.0` and `plugin-maven 2.30.0`.
