### PR TITLE
Gradle/Groovy importOrder no longer adds semicolons

### LINKED ISSUE #237: Groovy's "apply" adds semicolons
I have a custom `importOrder` for `groovy` and when I do a `gradle spotlessApply` it fixes that but it also adds semicolons to all import statements which it should not do.

P.S. I see now that actually this could be configured using Eclipse's Groovy plugin - however I don't see how to export Grvooy's formatter settings - rather, I see only how to do so for Java's.

P.S. 2 - I found [some link](https://github.com/SAP/cloud-s4-sdk-pipeline-lib/blob/master/greclipse.properties) with an example file so I'll be closing this issue. The link to `greclipse.properties` in the [README](https://github.com/diffplug/spotless/blob/master/plugin-gradle/README.md) is broken, you might want to fix that.

### PR DESCRIPTION
**Pull request by fvgh**
Gradle/Groovy `importOrder` no longer adds semicolons at end of statement.
Fixes #237 .

### CODE REVIEW

File: plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GroovyExtension.java [hunk 1]
```diff
@@ -73,16 +75,16 @@ public void importOrder(List<String> importOrder) {
 						"'importOrder([x, y, z])' is deprecated.",
 						"Use 'importOrder x, y, z' instead.",
 						"For details see https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-to-java-source"));
-		addStep(ImportOrderStep.createFromOrder(importOrder));
+		importOrder(importOrder.toArray(new String[0]));
 	}
 
 	public void importOrder(String... importOrder) {
-		addStep(ImportOrderStep.createFromOrder(importOrder));
+		addStep(importOrderStepFactory.createFrom(importOrder));
```
Comment (nedtwigg) [inline plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GroovyExtension.java]:
```java
class GroovyExtension {
  public void importOrderFile(String... importOrder) {
    addStep(ImportOrderStep.noSemicolon().createFrom(importOrder));
  }
```

Instance fields are state, and less state is better than more state.

File: lib/src/main/java/com/diffplug/spotless/java/ImportOrderStep.java [hunk 2]
```diff
@@ -35,33 +35,54 @@
 import com.diffplug.spotless.FormatterStep;
 
 public final class ImportOrderStep {
-	// prevent direct instantiation
-	private ImportOrderStep() {}
+	private final String lineFormat;
```
Comment (nedtwigg) [inline lib/src/main/java/com/diffplug/spotless/java/ImportOrderStep.java]: For the foreseeable future, I can only imagine two usages, `import %s` and `import %s;`.  How about this API, to help the code read a little more fluently, and also to keep the implementation a little more private.

```java
  private ImportOrderStep(String lineFormat) {
    this.lineFormat = lineFormat;
  }

  public static ImportOrderStep withSemicolon() {
    return new ImportOrderStep("import %s;");
  }

  public static ImportOrderStep noSemicolon() {
    return new ImportOrderStep("import %s");
  }  
```

File: plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GroovyExtension.java (hunk 1 above)
Comment (fvgh) [reply plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GroovyExtension.java]: Sorry @nedtwigg , I would prefer to keep #218 out, since the purpose is different. Furthermore this PR has only effect on `plugin-gradle` (well, it should :wink: ), whereas  #218 should be only documented in the `CHANGES.md` of `spotless`.
