### PR TITLE
Fix javadoc publishing

### LINKED ISSUE #775: Javadoc AccessDenied error
Just a quick heads up that the link to Spotless [Javadoc](https://javadoc.io/static/com.diffplug.spotless/spotless-plugin-gradle/5.7.0/com/diffplug/gradle/spotless/JavaExtension.html) is currently not working.

The origin of the hyperlink is from the [Java section](https://github.com/diffplug/spotless/tree/master/plugin-gradle#java) of `spotless/gradle-plugin` Readme.

### PR DESCRIPTION
**Pull request by nedtwigg**
I think this should fix #775.

The problem was that the doclet we used to put markdown into our javadoc required JDK8, so we just disabled the javadoc task on non-JDK8 machines. Rather than figure out how to get the doclet working on JDK11 or change our publishing JDK, I just removed the doclet and replaced the markdown-style code ticks with javadoc-style `{@code` blocks. I wish javadoc supported markdown, but it's not worth fighting the ecosystem over it.

### CODE REVIEW

File: lib-extra/src/main/java/com/diffplug/spotless/extra/GitAttributesLineEndings.java [hunk 1]
```diff
@@ -56,7 +56,7 @@
 
 /**
  * Uses [.gitattributes](https://git-scm.com/docs/gitattributes) to determine
```
Comment (jbduncan) [inline lib-extra/src/main/java/com/diffplug/spotless/extra/GitAttributesLineEndings.java:58]: I wonder if this markdown link should be an HTML one like `<a href="https://git-scm.com/docs/gitattributes">.gitattributes</a>`, with ".gitattributes" optionally wrapped in a `{@code ... }` block. What do you think?

File: plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java [hunk 2]
```diff
@@ -743,12 +743,12 @@ protected Project getProject() {
...
 	 * Most users will not want this method.  In the rare case that you want to create
-	 * a `SpotlessApply` which is independent of the normal Spotless machinery, this will
+	 * a {@code SpotlessApply} which is independent of the normal Spotless machinery, this will
 	 * let you do that.
 	 *
-	 * The returned task will not be hooked up to the global `spotlessApply`, and there will be no corresponding `check` task.
+	 * The returned task will not be hooked up to the global {@code spotlessApply}, and there will be no corresponding {@code check} task.
 	 *
-	 * NOTE: does not respect the rarely-used [`spotlessFiles` property](https://github.com/diffplug/spotless/blob/b7f8c551a97dcb92cc4b0ee665448da5013b30a3/plugin-gradle/README.md#can-i-apply-spotless-to-specific-files).
+	 * NOTE: does not respect the rarely-used [{@code spotlessFiles} property](https://github.com/diffplug/spotless/blob/b7f8c551a97dcb92cc4b0ee665448da5013b30a3/plugin-gradle/README.md#can-i-apply-spotless-to-specific-files).
```
Comment (jbduncan) [inline plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java:751]: I wonder if this link should also be changed to use `<a href="...">...</a>` syntax. Thoughts?

**Review by jbduncan — COMMENTED** [review]
Just a couple of nit-related comments from me, but otherwise this change seems very pragmatic to me. Well done! 👍

File: lib-extra/src/main/java/com/diffplug/spotless/extra/GitAttributesLineEndings.java (hunk 1 above)
Comment (nedtwigg) [reply lib-extra/src/main/java/com/diffplug/spotless/extra/GitAttributesLineEndings.java:58]: Thanks, good catch! I just fixed this with a regex in https://github.com/diffplug/spotless/pull/917.

File: plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java (hunk 2 above)
Comment (nedtwigg) [reply plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java:751]: Good call, same a bove.
