### PR TITLE
1480 speedup npm install step for npm based formatters

### LINKED ISSUE #1480: Speedup "npm install" step for npm-based formatters
From discussion in #1453 

Npm-based formatters require an npm install call to prepare running the npm process for formatting.
It would be nice if we could speedup that part (or alltogether prevent it, if it is not needed).
Some ideas:

1. Store the `node_modules`-directory and `package.json` somewhere in build-folder and copy/link those on later calls.
2. Similar, but more longevity: Store these folders/files somewhere in `$HOME/.cache/spotless/npm` and reuse/copy/link them from there? 
3. Gradle-specific: Leverage gradle's build-cache by creating a gradle task that generates the `package.json` and `node_modules` dir as (cachable) output. A second/third run would then just receive these files/folders from the build cache?

### LINKED ISSUE #1582: spotless-maven-plugin 2.33.0 spams the Maven log
- [ ] summary of problem

Since I've upgraded to spotless-maven-plugin 2.33.0, Spotless spams the Maven log with messages about formatting specific files. 2.32.0 didn't do this.

- [ ] gradle or maven version

Maven 3.8.7

- [ ] spotless version

2.33.0 of the spotless-maven-plugin, with prettier 2.5.1 and prettier-java 1.6.1

- [ ] operating system and version

Fedora Linux 37

- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

```xml
<plugin>
    <groupId>com.diffplug.spotless</groupId>
    <artifactId>spotless-maven-plugin</artifactId>
    <version>${version.spotless.maven}</version>
    <configuration>
        <formats>
            <format>
                <includes>
                    <include>src/*/java/**/*.java</include>
                </includes>
                <prettier>
                    <devDependencies>
                        <prettier>${version.spotless.prettier}</prettier>
                        <prettier-plugin-java>${version.spotless.prettier-java}</prettier-plugin-java>
                    </devDependencies>
                    <config>
                        <!-- Changes here must be reflected in .prettierrc.yml -->
                        <tabWidth>4</tabWidth>
                        <printWidth>100</printWidth>
                        <trailingComma>none</trailingComma>
                    </config>
                </prettier>
            </format>
        </formats>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Public repo: https://github.com/jqno/equalsverifier/

You can reproduce it by running `mvn clean verify` on the repo

- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

```
[INFO] creating formatter function (starting server)
[INFO] Preparing NodeServerLayout[nodeModulesDir=/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/target/spotless-prettier-node-modules-ad1e3c72c0bfb53668bed27bc1ffe070, packageJsonFile=/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/target/spotless-prettier-node-modules-ad1e3c72c0bfb53668bed27bc1ffe070/package.json, serveJsFile=/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/target/spotless-prettier-node-modules-ad1e3c72c0bfb53668bed27bc1ffe070/serve.js, npmrcFile=/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/target/spotless-prettier-node-modules-ad1e3c72c0bfb53668bed27bc1ffe070/.npmrc] for npm step com.diffplug.spotless.npm.PrettierFormatterStep$State.
[INFO] Prepared NodeServerLayout[nodeModulesDir=/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/target/spotless-prettier-node-modules-ad1e3c72c0bfb53668bed27bc1ffe070, packageJsonFile=/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/target/spotless-prettier-node-modules-ad1e3c72c0bfb53668bed27bc1ffe070/package.json, serveJsFile=/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/target/spotless-prettier-node-modules-ad1e3c72c0bfb53668bed27bc1ffe070/serve.js, npmrcFile=/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/target/spotless-prettier-node-modules-ad1e3c72c0bfb53668bed27bc1ffe070/.npmrc] for npm step com.diffplug.spotless.npm.PrettierFormatterStep$State in 0 ms.
[INFO] running npm install in /home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/target/spotless-prettier-node-modules-ad1e3c72c0bfb53668bed27bc1ffe070 for npm step com.diffplug.spotless.npm.PrettierFormatterStep$State
[INFO] npm install finished in 1057 ms in /home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/target/spotless-prettier-node-modules-ad1e3c72c0bfb53668bed27bc1ffe070 for npm step com.diffplug.spotless.npm.PrettierFormatterStep$State
[INFO] formatting String 'package nl.jqno.equalsverifier;

import edu.umd.cs[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/EqualsVerifierReport.java'
[INFO] formatting String 'package nl.jqno.equalsverifier;

import java.util.[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/Func.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.api;

import nl.jqn[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/api/EqualsVerifierApi.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.api;

import static[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/api/RelaxedEqualsVerifierApi.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.api;

import java.u[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/api/MultipleTypeEqualsVerifierApi.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.api;

import java.u[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/api/SingleTypeEqualsVerifierApi.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers;
[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/AbstractDelegationChecker.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers;
[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/CachedHashCodeChecker.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers;
[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/Checker.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers;
[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/ExamplesChecker.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers;
[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/FieldInspector.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers;
[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/HierarchyChecker.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers;
[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/MapEntryHashCodeRequirementChecker.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers;
[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/NullChecker.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers;
[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/RecordChecker.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers;
[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/SignatureChecker.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers.f[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/fieldchecks/ArrayFieldCheck.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers.f[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/fieldchecks/FieldCheck.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers.f[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/fieldchecks/FloatAndDoubleFieldCheck.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers.f[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/fieldchecks/MutableStateFieldCheck.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers.f[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/fieldchecks/ReflexivityFieldCheck.java'
[INFO] formatting String 'package nl.jqno.equalsverifier.internal.checkers.f[...]' in file '/home/jqno/w/equalsverifier/equalsverifier/equalsverifier-core/src/main/java/nl/jqno/equalsverifier/internal/checkers/fieldchecks/SymmetryFieldCheck.java'
```

...and a lot more of this.

### PR DESCRIPTION
**Pull request by simschla**
Provide an opt-in possibility to cache the result of `npm install` calls for the `npm`-based formatters. We are creating a copy of the resulting `node_modules` on first `npm install` and reuse that copy if we ever have to run `npm install` for the same `package.json` again.

Instead of just copying the files, we try to use hard links and only fall back to copy if that fails.

I've decided to make this an opt-in feature, I'm interested to hear your opinion on that @nedtwigg.

Resolves #1480. Resolves #1582.

### CODE REVIEW

File: lib/src/main/java/com/diffplug/spotless/TimedLogger.java [hunk 1]
```diff
@@ -0,0 +1,226 @@
...
+import java.util.stream.Stream;
+
+import javax.annotation.Nonnull;
+
+import org.slf4j.Logger;
+
+/**
+ * A logger that logs the time it took to execute a block of code.
+ */
+public class TimedLogger {
```
Comment (nedtwigg) [inline lib/src/main/java/com/diffplug/spotless/TimedLogger.java:31]: I would prefer this to be package-private, which would mean moving it to the package where it is actually used.

File: lib/src/main/java/com/diffplug/spotless/npm/ShadowCopy.java [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+			if (tryHardLink) {
+				try {
+					Files.createLink(target.toPath().resolve(orig.toPath().relativize(file)), file);
+					return super.visitFile(file, attrs);
+				} catch (UnsupportedOperationException | SecurityException | FileSystemException e) {
+					logger.debug("Shadow copy entry does not support hard links: {}. Switching to 'copy'.", file, e);
+					tryHardLink = false; // remember that hard links are not supported
+				} catch (IOException e) {
+					logger.debug("Shadow copy entry failed to create hard link: {}. Switching to 'copy'.", file, e);
+					tryHardLink = false; // remember that hard links are not supported
```
Comment (nedtwigg) [inline lib/src/main/java/com/diffplug/spotless/npm/ShadowCopy.java:153]: Neat!

**Review by nedtwigg — CHANGES_REQUESTED** [review]
This is great! My only feedback is about keeping our public API small by moving `TimedLogger` into the `npm` package.

File: lib/src/main/java/com/diffplug/spotless/TimedLogger.java (hunk 1 above)
Comment (simschla) [reply lib/src/main/java/com/diffplug/spotless/TimedLogger.java:31]: I kind of made that public on purpose thinking that this might be useful in other cases, too. If you prefer, I'll change it to package private no problem 😄

**Review by nedtwigg — APPROVED** [review]
Awesome, thanks!
