### PR TITLE
Common filter for files not supported by LicenseHeaderStep

### LINKED ISSUE #270: License Header task can't find regex `^package` in module-info.java and fails
The spotless license task blows up when it hits a `module-info.java` file

```
Step 'licenseHeader' found problem in 'Algorithms/BisectionBandwidth/src/main/module/module-info.java':
Unable to find delimiter regex ^package
java.lang.IllegalArgumentException: Unable to find delimiter regex ^package
        at com.diffplug.spotless.generic.LicenseHeaderStep.format(LicenseHeaderStep.java:121)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.FilterByFileFormatterStep.format(FilterByFileFormatterStep.java:42)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.Formatter.isClean(Formatter.java:167)
        at com.diffplug.gradle.spotless.SpotlessTask.check(SpotlessTask.java:263)
        at com.diffplug.gradle.spotless.SpotlessTask.performAction(SpotlessTask.java:205)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:105)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:273)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:258)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

Spotless version `3.10.0`.

Not sure if I'm going to have time to fix this one myself.

### PR DESCRIPTION
**Pull request by lutovich**
Extracted the filter into a shared constant which is used by all Gradle extensions and Maven mojo.

Resolves #270

### CODE REVIEW

File: lib/src/main/java/com/diffplug/spotless/generic/GenericConstants.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+	 * See:
+	 * <ul>
+	 * <li><a href="https://github.com/diffplug/spotless/issues/1">https://github.com/diffplug/spotless/issues/1</a></li>
+	 * <li><a href="https://github.com/diffplug/spotless/issues/270">https://github.com/diffplug/spotless/issues/270</a></li>
+	 * </ul>
+	 */
+	public static final SerializableFileFilter LISENCE_HEADER_UNSUPPORTED_FILES_FILTER = SerializableFileFilter.skipFilesNamed(
+			"package-info.java", "package-info.groovy", "module-info.java");
+
+	private GenericConstants() {}
```
Comment (nedtwigg) [inline lib/src/main/java/com/diffplug/spotless/generic/GenericConstants.java]: - `LISENCE` ought to be spelled `LICENSE`
-  This ought to live in  `LicenseHeaderStep` as `JAVA_FILES_SKIP` or something like that
- It should be exposed as a `public static SerializableFileFilter method();` rather than `public static final SerializableFileFilter field;`.  Changing the value of a public compile-time constant [breaks binary compatibility](https://wiki.eclipse.org/Evolving_Java-based_APIs_2#Evolving_API_interfaces_-_API_fields).

Comment (lutovich) [reply lib/src/main/java/com/diffplug/spotless/generic/GenericConstants.java]: Should be fixed now. The field is called `UNSUPPORTED_FILES_FILTER` and method that exposes it is `LicenseHeaderStep#unsupportedFilesFilter()`.  Wdyt?

Would such added `public static final` field become part of the public API? Who is the consumer of this API?

Comment (nedtwigg) [reply lib/src/main/java/com/diffplug/spotless/generic/GenericConstants.java]: > Would such added public static final field become part of the public API?

Yup, if anyone else compiles code against this, the value of the constant gets compiled into their code.  If we change the value of the constant, their code won't change.  Putting it behind a method call fixes this.

> Who is the consumer of this API?

Nobody that I know of.  We can be pretty cavalier about breaking ABI and we'd get away with it, but when it's easy to keep ABI then we might as well.

> `unsupportedFilesFilter()`

The trouble is that `LicenseHeaderStep` is used for lots of different languages, and this constant is Java-specific.  If we need a different filter for Kotlin or Scala or something, how would we name it?  How about `unsupportedJavaFilesFilter()`?

Comment (lutovich) [reply lib/src/main/java/com/diffplug/spotless/generic/GenericConstants.java]: I get the ABI point now. Thanks for the explanation.

Filter also excludes `package-info.groovy` that is why I tried not to mention Java in the method name :) Maybe it could be a single filter of all unsupported files?

Comment (nedtwigg) [reply lib/src/main/java/com/diffplug/spotless/generic/GenericConstants.java]: How about `unsupportedJvmFilesFilter()`?  We've open PR's for `c/c++` and `typescript` formatters.  It's easier to build it modular now, and have the option to return the same filter for each method, rather than to build it coupled, and have to deprecate later if we need to uncouple.

Comment (lutovich) [reply lib/src/main/java/com/diffplug/spotless/generic/GenericConstants.java]: `unsupportedJvmFilesFilter()` looks good to me. Updated the commit.

**Comment by nedtwigg** [comment]
Looks great!  Sorry to nitpick so much for a small change :)
